"""add schedule fields and release_links

Revision ID: 458f191776d4
Revises: 457a17c8e1e3
Create Date: 2026-08-25 00:01:22.290870
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "458f191776d4"
down_revision: str | None = "457a17c8e1e3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Alembic 은 CHECK 제약의 **내용 변경**을 감지하지 못한다 (신규 추가만 감지).
    # 시각 기반 이벤트 3종(SCHEDULE_ADDED / PREORDER_OPENS_SOON / RELEASED)을 허용하려면
    # 기존 제약을 직접 교체해야 한다 (ADR-0005).
    op.drop_constraint("event_type_valid", "listing_events", type_="check")
    op.create_check_constraint(
        "event_type_valid",
        "listing_events",
        "event_type IN ('SCHEDULE_ADDED','PREORDER_OPENS_SOON','PREORDER_OPEN','RELEASED','NEW_LISTING','RESTOCK','SOLD_OUT','PRICE_DROP','PRICE_RISE','DELISTED')",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "release_links",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("release_id", sa.BigInteger(), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=True),
        sa.Column("shop_name", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("price_krw", sa.Numeric(precision=12, scale=0), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
            name=op.f("fk_release_links_release_id_releases"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_release_links_source_id_sources"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_release_links")),
        sa.UniqueConstraint(
            "release_id", "url", name="uq_release_links_release_id_url"
        ),
    )
    op.create_index(
        "ix_release_links_release_id", "release_links", ["release_id"], unique=False
    )
    op.alter_column(
        "listing_events", "listing_id", existing_type=sa.BIGINT(), nullable=True
    )
    op.create_check_constraint(
        op.f("ck_listing_events_anchor_required"),
        "listing_events",
        "listing_id IS NOT NULL OR release_id IS NOT NULL",
    )
    op.add_column(
        "releases",
        sa.Column("preorder_opens_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "releases",
        sa.Column("preorder_closes_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "releases",
        sa.Column("curation", sa.Text(), server_default="MANUAL", nullable=False),
    )
    op.add_column(
        "releases",
        sa.Column("is_published", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column("releases", sa.Column("notes", sa.Text(), nullable=True))
    op.create_check_constraint(
        op.f("ck_releases_curation_valid"),
        "releases",
        "curation IN ('MANUAL','CRAWLED')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint("event_type_valid", "listing_events", type_="check")
    op.create_check_constraint(
        "event_type_valid",
        "listing_events",
        "event_type IN ('NEW_LISTING','PREORDER_OPEN','RESTOCK','SOLD_OUT','PRICE_DROP','PRICE_RISE','DELISTED')",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_releases_curation_valid"), "releases", type_="check")
    op.drop_column("releases", "notes")
    op.drop_column("releases", "is_published")
    op.drop_column("releases", "curation")
    op.drop_column("releases", "preorder_closes_at")
    op.drop_column("releases", "preorder_opens_at")
    op.drop_constraint(
        op.f("ck_listing_events_anchor_required"), "listing_events", type_="check"
    )
    op.alter_column(
        "listing_events", "listing_id", existing_type=sa.BIGINT(), nullable=False
    )
    op.drop_index("ix_release_links_release_id", table_name="release_links")
    op.drop_table("release_links")
    # ### end Alembic commands ###
