"""initial schema

Revision ID: 457a17c8e1e3
Revises:
Create Date: 2026-08-20 06:39:29.600890
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "457a17c8e1e3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # 확장을 가장 먼저 만든다. gin_trgm_ops 인덱스가 pg_trgm 에 의존하므로
    # 순서가 바뀌면 이 마이그레이션은 실패한다 (블루프린트 §4.2).
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artists",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name_display", sa.Text(), nullable=False),
        sa.Column("name_ko", sa.Text(), nullable=True),
        sa.Column("name_en", sa.Text(), nullable=True),
        sa.Column("name_norm", sa.Text(), nullable=False),
        sa.Column("mbid", sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artists")),
        sa.UniqueConstraint("mbid", name=op.f("uq_artists_mbid")),
        sa.UniqueConstraint("name_norm", name="uq_artists_name_norm"),
    )
    op.create_index(
        "ix_artists_name_norm_trgm",
        "artists",
        ["name_norm"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name_norm": "gin_trgm_ops"},
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column(
            "crawl_interval_sec", sa.Integer(), server_default="1800", nullable=False
        ),
        sa.Column("is_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("disabled_reason", sa.Text(), nullable=True),
        sa.Column("last_crawled_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "kind IN ('shop','label','distributor')", name=op.f("ck_sources_kind_valid")
        ),
        sa.CheckConstraint(
            "crawl_interval_sec >= 300", name=op.f("ck_sources_crawl_interval_min")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("apple_sub", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("apple_sub", name=op.f("uq_users_apple_sub")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "device_tokens",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("platform", sa.Text(), nullable=False),
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "platform IN ('IOS','WEB')", name=op.f("ck_device_tokens_platform_valid")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_device_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_tokens")),
        sa.UniqueConstraint(
            "platform", "token", name="uq_device_tokens_platform_token"
        ),
    )
    op.create_table(
        "raw_snapshots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("body_path", sa.Text(), nullable=True),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_raw_snapshots_source_id_sources"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_snapshots")),
    )
    op.create_index(
        "ix_raw_snapshots_content_hash", "raw_snapshots", ["content_hash"], unique=False
    )
    op.create_index(
        "ix_raw_snapshots_source_id_fetched_at",
        "raw_snapshots",
        ["source_id", sa.literal_column("fetched_at DESC")],
        unique=False,
    )
    op.create_table(
        "releases",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("title_norm", sa.Text(), nullable=False),
        sa.Column("primary_artist_id", sa.BigInteger(), nullable=True),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("catalog_no", sa.Text(), nullable=True),
        sa.Column("barcode", sa.Text(), nullable=True),
        sa.Column("format", sa.Text(), nullable=True),
        sa.Column("variant", sa.Text(), nullable=True),
        sa.Column("is_limited", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column("discogs_id", sa.BigInteger(), nullable=True),
        sa.Column("cover_url", sa.Text(), nullable=True),
        sa.Column("master_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["master_id"], ["releases.id"], name=op.f("fk_releases_master_id_releases")
        ),
        sa.ForeignKeyConstraint(
            ["primary_artist_id"],
            ["artists.id"],
            name=op.f("fk_releases_primary_artist_id_artists"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_releases")),
    )
    op.create_index(
        "ix_releases_release_date",
        "releases",
        [sa.literal_column("release_date DESC NULLS LAST")],
        unique=False,
    )
    op.create_index(
        "ix_releases_title_norm_trgm",
        "releases",
        ["title_norm"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title_norm": "gin_trgm_ops"},
    )
    op.create_index(
        "uq_releases_barcode",
        "releases",
        ["barcode"],
        unique=True,
        postgresql_where=sa.text("barcode IS NOT NULL"),
    )
    op.create_table(
        "watchlist_items",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("target_type", sa.Text(), nullable=False),
        sa.Column("target_ref", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "target_type IN ('ARTIST','LABEL','RELEASE','KEYWORD')",
            name=op.f("ck_watchlist_items_target_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_watchlist_items_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watchlist_items")),
        sa.UniqueConstraint(
            "user_id",
            "target_type",
            "target_ref",
            name="uq_watchlist_items_user_target",
        ),
    )
    op.create_table(
        "listings",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("source_item_id", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("release_id", sa.BigInteger(), nullable=True),
        sa.Column("title_raw", sa.Text(), nullable=False),
        sa.Column("artist_raw", sa.Text(), nullable=True),
        sa.Column("label_raw", sa.Text(), nullable=True),
        sa.Column("price_krw", sa.Numeric(precision=12, scale=0), nullable=True),
        sa.Column("stock_status", sa.Text(), nullable=False),
        sa.Column("format_raw", sa.Text(), nullable=True),
        sa.Column("release_date_raw", sa.Text(), nullable=True),
        sa.Column("thumbnail_url", sa.Text(), nullable=True),
        sa.Column(
            "extra",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
            name=op.f("fk_listings_release_id_releases"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_listings_source_id_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listings")),
        sa.UniqueConstraint(
            "source_id", "source_item_id", name="uq_listings_source_id_source_item_id"
        ),
    )
    op.create_index(
        "ix_listings_first_seen_at",
        "listings",
        [sa.literal_column("first_seen_at DESC")],
        unique=False,
    )
    op.create_index("ix_listings_release_id", "listings", ["release_id"], unique=False)
    op.create_index(
        "ix_listings_stock_status",
        "listings",
        ["stock_status"],
        unique=False,
        postgresql_where=sa.text("stock_status IN ('PREORDER','IN_STOCK')"),
    )
    op.create_table(
        "release_artists",
        sa.Column("release_id", sa.BigInteger(), nullable=False),
        sa.Column("artist_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.Text(), server_default="primary", nullable=False),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
            name=op.f("fk_release_artists_artist_id_artists"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
            name=op.f("fk_release_artists_release_id_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "release_id", "artist_id", "role", name=op.f("pk_release_artists")
        ),
    )
    op.create_table(
        "listing_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("listing_id", sa.BigInteger(), nullable=False),
        sa.Column("release_id", sa.BigInteger(), nullable=True),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("old_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("new_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type IN ('NEW_LISTING','PREORDER_OPEN','RESTOCK','SOLD_OUT','PRICE_DROP','PRICE_RISE','DELISTED')",
            name=op.f("ck_listing_events_event_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_listing_events_listing_id_listings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
            name=op.f("fk_listing_events_release_id_releases"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listing_events")),
    )
    op.create_index(
        "ix_listing_events_occurred_at",
        "listing_events",
        [sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_listing_events_release_id_occurred_at",
        "listing_events",
        ["release_id", sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_table(
        "merge_candidates",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("listing_id", sa.BigInteger(), nullable=False),
        sa.Column("release_id", sa.BigInteger(), nullable=False),
        sa.Column("score", sa.REAL(), nullable=False),
        sa.Column("method", sa.Text(), nullable=False),
        sa.Column("resolved", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_merge_candidates_listing_id_listings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
            name=op.f("fk_merge_candidates_release_id_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_merge_candidates")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # pg_trgm / unaccent 는 삭제하지 않는다. 데이터베이스 전역 객체라
    # 다른 스키마가 쓰고 있을 수 있고, 되살리는 비용도 사실상 없다.

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("merge_candidates")
    op.drop_index(
        "ix_listing_events_release_id_occurred_at", table_name="listing_events"
    )
    op.drop_index("ix_listing_events_occurred_at", table_name="listing_events")
    op.drop_table("listing_events")
    op.drop_table("release_artists")
    op.drop_index(
        "ix_listings_stock_status",
        table_name="listings",
        postgresql_where=sa.text("stock_status IN ('PREORDER','IN_STOCK')"),
    )
    op.drop_index("ix_listings_release_id", table_name="listings")
    op.drop_index("ix_listings_first_seen_at", table_name="listings")
    op.drop_table("listings")
    op.drop_table("watchlist_items")
    op.drop_index(
        "uq_releases_barcode",
        table_name="releases",
        postgresql_where=sa.text("barcode IS NOT NULL"),
    )
    op.drop_index(
        "ix_releases_title_norm_trgm",
        table_name="releases",
        postgresql_using="gin",
        postgresql_ops={"title_norm": "gin_trgm_ops"},
    )
    op.drop_index("ix_releases_release_date", table_name="releases")
    op.drop_table("releases")
    op.drop_index("ix_raw_snapshots_source_id_fetched_at", table_name="raw_snapshots")
    op.drop_index("ix_raw_snapshots_content_hash", table_name="raw_snapshots")
    op.drop_table("raw_snapshots")
    op.drop_table("device_tokens")
    op.drop_table("users")
    op.drop_table("sources")
    op.drop_index(
        "ix_artists_name_norm_trgm",
        table_name="artists",
        postgresql_using="gin",
        postgresql_ops={"name_norm": "gin_trgm_ops"},
    )
    op.drop_table("artists")
    # ### end Alembic commands ###
