"""web push subscriptions and delivery log

Revision ID: 5344203b6f27
Revises: 458f191776d4
Create Date: 2026-09-07 06:53:48.612735
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5344203b6f27"
down_revision: str | None = "458f191776d4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_deliveries",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.BigInteger(), nullable=False),
        sa.Column("device_token_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.Text(), server_default="PENDING", nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PENDING','SENT','FAILED','EXPIRED')",
            name=op.f("ck_notification_deliveries_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["device_token_id"],
            ["device_tokens.id"],
            name=op.f("fk_notification_deliveries_device_token_id_device_tokens"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["listing_events.id"],
            name=op.f("fk_notification_deliveries_event_id_listing_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_deliveries")),
        sa.UniqueConstraint(
            "event_id", "device_token_id", name="uq_deliveries_event_device"
        ),
    )
    op.create_index(
        "ix_notification_deliveries_status_created_at",
        "notification_deliveries",
        ["status", "created_at"],
        unique=False,
    )
    op.add_column("device_tokens", sa.Column("p256dh", sa.Text(), nullable=True))
    op.add_column("device_tokens", sa.Column("auth", sa.Text(), nullable=True))
    op.add_column(
        "device_tokens",
        sa.Column("failure_count", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "device_tokens",
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "device_tokens",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "device_tokens", "user_id", existing_type=sa.BIGINT(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "device_tokens", "user_id", existing_type=sa.BIGINT(), nullable=False
    )
    op.drop_column("device_tokens", "created_at")
    op.drop_column("device_tokens", "last_success_at")
    op.drop_column("device_tokens", "failure_count")
    op.drop_column("device_tokens", "auth")
    op.drop_column("device_tokens", "p256dh")
    op.drop_index(
        "ix_notification_deliveries_status_created_at",
        table_name="notification_deliveries",
    )
    op.drop_table("notification_deliveries")
    # ### end Alembic commands ###
