/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Releases
         * @description 초안을 포함한 전체 일정.
         */
        get: operations["list_releases_admin_releases_get"];
        put?: never;
        /**
         * Create Release
         * @description 일정을 등록한다. **기본은 초안**이며 공개하려면 별도 호출이 필요하다.
         */
        post: operations["create_release_admin_releases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/releases/{release_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Release
         * @description 일정 하나. 초안이어도 운영자에게는 보인다 (공개 API 와 다른 점).
         */
        get: operations["get_release_admin_releases__release_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Release
         * @description **초안만** 삭제할 수 있다. 공개 중이면 먼저 공개를 취소해야 한다 (T-133).
         *
         *     이전에는 "한 번도 공개된 적 없는" 것만 지울 수 있었다. 발송 이력을 지키려는
         *     규칙이었지만, 그 결과 **운영자가 남은 방법이 SQL 뿐**이 되었다.
         *     손으로 여러 테이블을 순서대로 지우는 쪽이 훨씬 위험하다 — 한 줄 틀리면
         *     남의 데이터까지 지운다. 그래서 가드를 여기로 옮긴다.
         *
         *     **공개 중인 것은 여전히 못 지운다.** 공개 취소를 한 번 거치게 해서,
         *     실수로 살아 있는 일정을 지우는 일이 없도록 한 단계를 남긴다.
         *
         *     감수하는 것 — 이 발매에 대해 **무엇을 언제 보냈는지 기록이 사라진다.**
         *     `notification_deliveries` 는 `listing_events` 의 CASCADE 로 함께 지워진다.
         */
        delete: operations["delete_release_admin_releases__release_id__delete"];
        options?: never;
        head?: never;
        /** Update Release */
        patch: operations["update_release_admin_releases__release_id__patch"];
        trace?: never;
    };
    "/admin/releases/{release_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish Release
         * @description 공개한다. 이 시점에 `SCHEDULE_ADDED` 이벤트가 **한 번만** 생긴다.
         */
        post: operations["publish_release_admin_releases__release_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/releases/{release_id}/unpublish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unpublish Release
         * @description 공개를 취소해 초안으로 되돌린다.
         *
         *     잘못 공개한 일정을 되돌릴 수단이 없으면 삭제도 못 한다
         *     (공개본 삭제는 409 로 막혀 있다).
         *
         *     **이미 나간 `SCHEDULE_ADDED` 이벤트는 지우지 않는다.** 구독자에게 전달된 사실은
         *     남아야 하고, 다시 공개해도 이벤트가 또 생기지는 않는다.
         */
        post: operations["unpublish_release_admin_releases__release_id__unpublish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/releases/{release_id}/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Link */
        post: operations["add_link_admin_releases__release_id__links_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/releases/{release_id}/links/{link_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Link
         * @description 구매처 링크를 지운다. 여러 개를 등록할 수 있으니 지우는 수단도 있어야 한다.
         */
        delete: operations["delete_link_admin_releases__release_id__links__link_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Releases
         * @description 공개된 발매 일정 목록.
         *
         *     정렬은 **예약 시작이 임박한 순**이며, 날짜 미정 일정은 맨 뒤로 간다.
         */
        get: operations["list_releases_v1_releases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/releases/{release_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Release
         * @description 공개된 일정 하나.
         *
         *     초안은 **404** 로 응답한다 — 403 으로 구분하면 "존재는 한다"는 사실이 새어 나간다.
         */
        get: operations["get_release_v1_releases__release_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Feed
         * @description 중복 제거와 정렬을 LIMIT 전에 적용한다.
         */
        get: operations["get_feed_v1_feed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/releases.ics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Releases Ics
         * @description 공개된 일정을 iCalendar 로 반환한다. 캘린더 앱에서 **구독** 하면 된다.
         */
        get: operations["releases_ics_v1_releases_ics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/feed.rss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Feed Rss
         * @description 공개된 일정의 이벤트를 RSS 2.0 으로 반환한다.
         */
        get: operations["feed_rss_v1_feed_rss_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/push/public-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Public Key
         * @description 브라우저가 구독할 때 필요한 VAPID 공개키.
         *
         *     키가 없으면 `enabled=false` 를 돌려준다 — 클라이언트가 구독 버튼을 감출 수 있도록.
         *     오류로 다루지 않는 이유는 푸시가 없어도 나머지 기능은 멀쩡하기 때문이다.
         */
        get: operations["public_key_v1_push_public_key_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/push/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Subscribe
         * @description 구독을 등록한다.
         *
         *     같은 엔드포인트로 다시 구독하면 **오류가 아니라 갱신**이다. 브라우저는 권한을
         *     다시 물을 때마다 같은 구독을 돌려주므로, 중복 요청이 정상 경로다.
         */
        post: operations["subscribe_v1_push_subscribe_post"];
        /**
         * Unsubscribe
         * @description 구독을 해지한다.
         *
         *     행을 지우지 않고 **비활성화**한다 — 이미 보낸 기록(`notification_deliveries`)이
         *     참조하고 있고, 무엇을 언제 보냈는지는 남아야 한다.
         *     없는 엔드포인트를 해지해도 204 다 (멱등).
         */
        delete: operations["unsubscribe_v1_push_subscribe_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description 헬스체크. 블루프린트 §5.2 에 따라 **DB 연결까지 확인**한다.
         *
         *     DB 가 응답하지 않으면 503 을 반환한다. 배포 검증(§9.5)이 이 응답에 의존하므로
         *     DB 장애를 200 으로 감추지 않는다.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Curation
         * @description 일정의 출처. `releases.curation` (ADR-0005).
         *
         *     수동 등록분과 크롤 산출물이 같은 테이블에 병존하므로 구분이 필요하다.
         * @enum {string}
         */
        Curation: "MANUAL" | "CRAWLED";
        /**
         * EventType
         * @description 이벤트 종류. `listing_events.event_type`.
         *
         *     두 갈래가 있다 (ADR-0005):
         *     - **시각 기반** — 운영자가 입력한 일정에서 스케줄러가 생성한다. diff 가 필요 없다
         *     - **diff 기반** — 크롤 결과를 직전 상태와 비교해 생성한다 (M3)
         * @enum {string}
         */
        EventType: "SCHEDULE_ADDED" | "SCHEDULE_CHANGED" | "PREORDER_OPENS_SOON" | "PREORDER_OPEN" | "RELEASED" | "NEW_LISTING" | "RESTOCK" | "SOLD_OUT" | "PRICE_DROP" | "PRICE_RISE" | "DELISTED";
        /**
         * FeedItem
         * @description 피드 한 줄.
         */
        FeedItem: {
            kind: components["schemas"]["FeedKind"];
            /**
             * At
             * Format: date-time
             * @description UPCOMING 이면 예약 시작 시각, EVENT 면 발생 시각
             */
            at: string;
            event_type?: components["schemas"]["EventType"] | null;
            release: components["schemas"]["ReleaseOut"];
        };
        /**
         * FeedKind
         * @description 피드 항목의 종류.
         * @enum {string}
         */
        FeedKind: "UPCOMING" | "EVENT";
        /** FeedPage */
        FeedPage: {
            /** Items */
            items: components["schemas"]["FeedItem"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description `/healthz` 응답 본문.
         */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "unavailable";
            /** Version */
            version: string;
        };
        /**
         * PushKeys
         * @description 브라우저가 주는 암호화 키 (RFC 8291).
         */
        PushKeys: {
            /**
             * P256Dh
             * @description 구독 공개키
             */
            p256dh: string;
            /**
             * Auth
             * @description 인증 시크릿
             */
            auth: string;
        };
        /**
         * PushPublicKeyOut
         * @description 브라우저가 구독할 때 쓰는 VAPID 공개키.
         */
        PushPublicKeyOut: {
            /** Public Key */
            public_key: string;
            /**
             * Enabled
             * @description 서버에 키가 설정되어 있는지
             */
            enabled: boolean;
        };
        /**
         * PushSubscriptionIn
         * @description `PushSubscription.toJSON()` 이 그대로 들어온다.
         *
         *     브라우저가 만들어 주는 형태를 그대로 받으므로 클라이언트 코드가 단순해진다.
         */
        PushSubscriptionIn: {
            /**
             * Endpoint
             * @description 푸시 서비스 엔드포인트 URL
             */
            endpoint: string;
            keys: components["schemas"]["PushKeys"];
        };
        /** PushSubscriptionOut */
        PushSubscriptionOut: {
            /** Id */
            id: number;
            /** Endpoint */
            endpoint: string;
            /**
             * Created
             * @description 새로 만들어졌는지(False 면 이미 있던 구독)
             */
            created: boolean;
        };
        /**
         * PushUnsubscribeIn
         * @description 해지에는 엔드포인트만 있으면 된다.
         *
         *     여기서는 **호스트를 검사하지 않는다.** 조회만 하고 그 주소로 요청을 보내지
         *     않으므로 위험이 없고, 목록이 바뀌기 전에 등록된 구독도 해지할 수 있어야 한다.
         */
        PushUnsubscribeIn: {
            /** Endpoint */
            endpoint: string;
        };
        /**
         * ReleaseAdminOut
         * @description 운영자 응답. 메모까지 포함한다.
         */
        ReleaseAdminOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Artist Name */
            artist_name?: string | null;
            /** Label */
            label?: string | null;
            /** Format */
            format?: string | null;
            /** Variant */
            variant?: string | null;
            /** Is Limited */
            is_limited: boolean;
            /** Release Date */
            release_date?: string | null;
            /** Preorder Opens At */
            preorder_opens_at?: string | null;
            /** Preorder Closes At */
            preorder_closes_at?: string | null;
            /** Cover Url */
            cover_url?: string | null;
            curation: components["schemas"]["Curation"];
            /** Is Published */
            is_published: boolean;
            /** Links */
            links?: components["schemas"]["ReleaseLinkOut"][];
            /** Notes */
            notes?: string | null;
            /**
             * Can Delete
             * @description 비공개이며 연결된 수집 상품이 없어 삭제 가능한가
             * @default false
             */
            can_delete: boolean;
        };
        /**
         * ReleaseIn
         * @description 일정 등록 입력.
         *
         *     운영자가 채우는 값이다. `title` 외에는 전부 선택이며,
         *     **알림의 트리거는 `preorder_opens_at`** 이다.
         */
        ReleaseIn: {
            /** Title */
            title: string;
            /** Artist Name */
            artist_name?: string | null;
            /** Label */
            label?: string | null;
            /** Format */
            format?: string | null;
            /** Variant */
            variant?: string | null;
            /**
             * Is Limited
             * @default false
             */
            is_limited: boolean;
            /** Release Date */
            release_date?: string | null;
            /** Preorder Opens At */
            preorder_opens_at?: string | null;
            /** Preorder Closes At */
            preorder_closes_at?: string | null;
            /** Cover Url */
            cover_url?: string | null;
            /** Notes */
            notes?: string | null;
            /** Links */
            links?: components["schemas"]["ReleaseLinkIn"][];
        };
        /**
         * ReleaseLinkIn
         * @description 구매 링크 입력.
         */
        ReleaseLinkIn: {
            /** Shop Name */
            shop_name: string;
            /** Url */
            url: string;
            /** Source Id */
            source_id?: string | null;
            /** Price Krw */
            price_krw?: number | string | null;
        };
        /**
         * ReleaseLinkOut
         * @description 구매 링크 응답.
         *
         *     `price_krw` 를 `int` 로 내보낸다. `NUMERIC(12,0)` 을 그대로 직렬화하면
         *     Postgres 가 `Decimal('5E+4')` 로 돌려주어 `"5E+4"` 라는 값이 API 에 나간다.
         *     원화에는 소수 단위가 없으므로 정수가 정직한 타입이다.
         */
        ReleaseLinkOut: {
            /** Id */
            id: number;
            /** Shop Name */
            shop_name: string;
            /** Url */
            url: string;
            /** Source Id */
            source_id?: string | null;
            /** Price Krw */
            price_krw?: number | null;
        };
        /**
         * ReleaseOut
         * @description 공개 응답. `notes` 는 운영자 메모라 노출하지 않는다.
         */
        ReleaseOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Artist Name */
            artist_name?: string | null;
            /** Label */
            label?: string | null;
            /** Format */
            format?: string | null;
            /** Variant */
            variant?: string | null;
            /** Is Limited */
            is_limited: boolean;
            /** Release Date */
            release_date?: string | null;
            /** Preorder Opens At */
            preorder_opens_at?: string | null;
            /** Preorder Closes At */
            preorder_closes_at?: string | null;
            /** Cover Url */
            cover_url?: string | null;
            curation: components["schemas"]["Curation"];
            /** Is Published */
            is_published: boolean;
            /** Links */
            links?: components["schemas"]["ReleaseLinkOut"][];
        };
        /**
         * ReleasePage
         * @description 커서 페이지네이션 응답 (§5.1).
         */
        ReleasePage: {
            /** Items */
            items: components["schemas"]["ReleaseOut"][];
            /**
             * Next Cursor
             * @description 다음 페이지 커서. null 이면 마지막 페이지.
             */
            next_cursor?: string | null;
        };
        /**
         * ReleaseUpdate
         * @description 부분 수정. 보낸 필드만 바뀐다.
         */
        ReleaseUpdate: {
            /** Title */
            title?: string | null;
            /** Artist Name */
            artist_name?: string | null;
            /** Label */
            label?: string | null;
            /** Format */
            format?: string | null;
            /** Variant */
            variant?: string | null;
            /** Is Limited */
            is_limited?: boolean | null;
            /** Release Date */
            release_date?: string | null;
            /** Preorder Opens At */
            preorder_opens_at?: string | null;
            /** Preorder Closes At */
            preorder_closes_at?: string | null;
            /** Cover Url */
            cover_url?: string | null;
            /** Notes */
            notes?: string | null;
            /** Links */
            links?: components["schemas"]["ReleaseLinkIn"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_releases_admin_releases_get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseAdminOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_release_admin_releases_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReleaseIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_release_admin_releases__release_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path: {
                release_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_release_admin_releases__release_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path: {
                release_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_release_admin_releases__release_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path: {
                release_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReleaseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_release_admin_releases__release_id__publish_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path: {
                release_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unpublish_release_admin_releases__release_id__unpublish_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path: {
                release_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_link_admin_releases__release_id__links_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path: {
                release_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReleaseLinkIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseLinkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_link_admin_releases__release_id__links__link_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path: {
                release_id: number;
                link_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_releases_v1_releases_get: {
        parameters: {
            query?: {
                /** @description 이전 응답의 next_cursor */
                cursor?: string | null;
                limit?: number;
                from?: string | null;
                to?: string | null;
                format?: string | null;
                is_limited?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleasePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_release_v1_releases__release_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                release_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_feed_v1_feed_get: {
        parameters: {
            query?: {
                limit?: number;
                sort?: "recent" | "imminent";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    releases_ics_v1_releases_ics_get: {
        parameters: {
            query?: {
                /** @description 발매일도 종일 일정으로 포함할지 */
                include_release_dates?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description iCalendar 구독 피드 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/calendar": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feed_rss_v1_feed_rss_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RSS 2.0 피드 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/rss+xml": unknown;
                };
            };
        };
    };
    public_key_v1_push_public_key_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushPublicKeyOut"];
                };
            };
        };
    };
    subscribe_v1_push_subscribe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushSubscriptionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushSubscriptionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unsubscribe_v1_push_subscribe_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushUnsubscribeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
